### ISSUE TITLE
Comments in selector broken

### ISSUE THREAD

**Issue by darrenkopp** [darrenkopp/SassyStudio#21]
Comments in a multiline selector are broken. For example

``` CSS
button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
    -webkit-appearance: button; /* 2 */
    cursor: pointer; /* 3 */
}
```

This is likely due to the fact that the entire selector is formatted which overrides the comment formatting
