### ISSUE TITLE
When commenting code using keyboard shortcut place commenting symbols closely to actual code

### ISSUE THREAD

**Issue by mezzario** [darrenkopp/SassyStudio#55]
For example if I select ".collapsed-marker" block below and press **Ctrl+K, C** I will see this:

``` scss
body {
    background-color: #f1f4f6;

//  .collapsed-marker {
//      display: none;
//  }
}
```

And I suggest right behaviour is this:

``` scss
body {
    background-color: #f1f4f6;

    //.collapsed-marker {
    //  display: none;
    //}
}
```

With this approach it's easier to manage text blocks and it's how native commenting in Visual Studio is implemented.

Let me know if you have any questions and thank you :)
